# config.yaml
symbols: ["BTCUSDT", "TRXUSDT"]  # Để trống để quét tất cả cặp

# Chỉ 1 khung giờ duy nhất

timeframe: "10m"
signal_time_frame: "1m"

binance:
#  api_key: "nKOWiUgNxorRZtD8urVbwnaxk5WyJ70IRrvH0EqMl3PFucuVX5EuRQxrvPFH8A4v"
#  secret_key: "EetKj9b6w9R7BooFEjr8K31HpQbGn41PPVt2kBReoyep4mVIZODMtiWbjRYmQ6qn"
#  base_url: "https://testnet.binancefuture.com"
#  testnet: True

logging:
  level: "INFO"
  log_file: "candle_scanner.log"
  signals_log_file: "trading_signals.log"
  trading_log_file: "trading_results.log"
  max_file_size_mb: 100
  backup_count: 5

analysis:
  update_interval: 1.0
  max_symbols_per_connection: 200
  scan_all_pairs: false

trading:
  # Cấu hình risk management
  take_profit_percentage: 7  # TP 1.5%
  stop_loss_percentage: 35  # SL 1%
  leverage: 15  # ĐÒN BẨY 10x
  position_size_usdt: 0.5  # SỐ TIỀN MỖI LỆNH (QUAN TRỌNG)